"""add break_minutes to time_entries

Revision ID: 4602bd233158
Revises: b9b08ac1fed6
Create Date: 2026-04-26 07:43:27.480542

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4602bd233158'
down_revision: Union[str, None] = 'b9b08ac1fed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('time_entries', sa.Column('break_minutes', sa.Integer(), nullable=True))
    op.execute("UPDATE time_entries SET break_minutes = 0 WHERE break_minutes IS NULL")
    op.alter_column('time_entries', 'break_minutes', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entries', 'break_minutes')
    # ### end Alembic commands ###
